joint_limits:
  joint_1:
    has_velocity_limits:true
    max_velocity:2.13802833369305
    has_acceleration_limits:true
    max_acceleration:5.45886630146266
  joint_2:
    has_velocity_limits:true
    max_velocity:2.44346095279206
    has_acceleration_limits:true
    max_acceleration:5.45886630146266
  joint_3:
    has_velocity_limits:true
    max_velocity:2.44346095279206
    has_acceleration_limits:true
    max_acceleration:5.45886630146266
  joint_4:
    has_velocity_limits:true
    max_velocity:3.66519142918809
    has_acceleration_limits:true
    max_acceleration:8.27617678003191
  joint_5:
    has_velocity_limits:true
    max_velocity:3.66519142918809
    has_acceleration_limits:true
    max_acceleration:8.27617678003191
  joint_6:
    has_velocity_limits:true
    max_velocity:5.86430628670095
    has_acceleration_limits:true
    max_acceleration:13.2419875678062
